server:
  port: 9001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/
    register-with-eureka: false
  server:
    enable-self-preservation: false
      
spring:
  application:
    name: eurekaServer